# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eliassong/Desktop/MyHttpServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eliassong/Desktop/MyHttpServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eliassong/Desktop/MyHttpServer/CMakeFiles /home/eliassong/Desktop/MyHttpServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eliassong/Desktop/MyHttpServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SRC

# Build rule for target.
SRC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SRC
.PHONY : SRC

# fast build rule for target.
SRC/fast:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/build
.PHONY : SRC/fast

#=============================================================================
# Target rules for targets named myhttpd

# Build rule for target.
myhttpd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myhttpd
.PHONY : myhttpd

# fast build rule for target.
myhttpd/fast:
	$(MAKE) -f CMakeFiles/myhttpd.dir/build.make CMakeFiles/myhttpd.dir/build
.PHONY : myhttpd/fast

Connection.o: Connection.cpp.o

.PHONY : Connection.o

# target to build an object file
Connection.cpp.o:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/Connection.cpp.o
.PHONY : Connection.cpp.o

Connection.i: Connection.cpp.i

.PHONY : Connection.i

# target to preprocess a source file
Connection.cpp.i:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/Connection.cpp.i
.PHONY : Connection.cpp.i

Connection.s: Connection.cpp.s

.PHONY : Connection.s

# target to generate assembly for a file
Connection.cpp.s:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/Connection.cpp.s
.PHONY : Connection.cpp.s

MyConf.o: MyConf.cpp.o

.PHONY : MyConf.o

# target to build an object file
MyConf.cpp.o:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/MyConf.cpp.o
.PHONY : MyConf.cpp.o

MyConf.i: MyConf.cpp.i

.PHONY : MyConf.i

# target to preprocess a source file
MyConf.cpp.i:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/MyConf.cpp.i
.PHONY : MyConf.cpp.i

MyConf.s: MyConf.cpp.s

.PHONY : MyConf.s

# target to generate assembly for a file
MyConf.cpp.s:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/MyConf.cpp.s
.PHONY : MyConf.cpp.s

MyThread.o: MyThread.cpp.o

.PHONY : MyThread.o

# target to build an object file
MyThread.cpp.o:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/MyThread.cpp.o
.PHONY : MyThread.cpp.o

MyThread.i: MyThread.cpp.i

.PHONY : MyThread.i

# target to preprocess a source file
MyThread.cpp.i:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/MyThread.cpp.i
.PHONY : MyThread.cpp.i

MyThread.s: MyThread.cpp.s

.PHONY : MyThread.s

# target to generate assembly for a file
MyThread.cpp.s:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/MyThread.cpp.s
.PHONY : MyThread.cpp.s

MyThreadPool.o: MyThreadPool.cpp.o

.PHONY : MyThreadPool.o

# target to build an object file
MyThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/MyThreadPool.cpp.o
.PHONY : MyThreadPool.cpp.o

MyThreadPool.i: MyThreadPool.cpp.i

.PHONY : MyThreadPool.i

# target to preprocess a source file
MyThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/MyThreadPool.cpp.i
.PHONY : MyThreadPool.cpp.i

MyThreadPool.s: MyThreadPool.cpp.s

.PHONY : MyThreadPool.s

# target to generate assembly for a file
MyThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/MyThreadPool.cpp.s
.PHONY : MyThreadPool.cpp.s

TypeFactory.o: TypeFactory.cpp.o

.PHONY : TypeFactory.o

# target to build an object file
TypeFactory.cpp.o:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/TypeFactory.cpp.o
.PHONY : TypeFactory.cpp.o

TypeFactory.i: TypeFactory.cpp.i

.PHONY : TypeFactory.i

# target to preprocess a source file
TypeFactory.cpp.i:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/TypeFactory.cpp.i
.PHONY : TypeFactory.cpp.i

TypeFactory.s: TypeFactory.cpp.s

.PHONY : TypeFactory.s

# target to generate assembly for a file
TypeFactory.cpp.s:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/TypeFactory.cpp.s
.PHONY : TypeFactory.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/myhttpd.dir/build.make CMakeFiles/myhttpd.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/myhttpd.dir/build.make CMakeFiles/myhttpd.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SRC.dir/build.make CMakeFiles/SRC.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/myhttpd.dir/build.make CMakeFiles/myhttpd.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SRC"
	@echo "... myhttpd"
	@echo "... Connection.o"
	@echo "... Connection.i"
	@echo "... Connection.s"
	@echo "... MyConf.o"
	@echo "... MyConf.i"
	@echo "... MyConf.s"
	@echo "... MyThread.o"
	@echo "... MyThread.i"
	@echo "... MyThread.s"
	@echo "... MyThreadPool.o"
	@echo "... MyThreadPool.i"
	@echo "... MyThreadPool.s"
	@echo "... TypeFactory.o"
	@echo "... TypeFactory.i"
	@echo "... TypeFactory.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

